# Generated by Django 3.1.4 on 2020-12-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AgencyName', models.CharField(max_length=200)),
                ('AgencyIVA', models.IntegerField()),
                ('AgencyManagerId', models.CharField(max_length=20)),
                ('AgencyCertification', models.CharField(max_length=20)),
                ('AgencyAddress', models.CharField(max_length=200)),
                ('AgencyEmail', models.CharField(max_length=255)),
                ('AgencyPhone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClientName', models.CharField(max_length=255)),
                ('ClientSurname', models.CharField(max_length=255)),
                ('ClientFiscal', models.CharField(max_length=20)),
                ('ClientContact', models.CharField(max_length=200)),
                ('ClientContactAddress', models.CharField(max_length=200)),
                ('ClientContactEmail', models.CharField(max_length=255)),
                ('ClientContactPhone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('CustomerID', models.AutoField(primary_key=True, serialize=False)),
                ('CustomerName', models.CharField(max_length=200)),
                ('CustomerIVA', models.IntegerField(max_length=4)),
                ('CustomerAddress', models.CharField(max_length=200)),
                ('CustomerEmail', models.CharField(max_length=255)),
                ('CustomerPhone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('TicketId', models.AutoField(primary_key=True, serialize=False)),
                ('SalesPoint', models.CharField(max_length=255)),
                ('RequestType', models.CharField(max_length=20)),
                ('Priority', models.CharField(max_length=10)),
                ('TicketCode', models.CharField(max_length=100)),
                ('Client', models.CharField(max_length=200)),
                ('TicketDescrp', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=200)),
                ('UserEmail', models.CharField(max_length=255)),
                ('UserPassword', models.CharField(max_length=12)),
                ('UserRole', models.CharField(max_length=5)),
            ],
        ),
    ]
