# Generated by Django 3.1.4 on 2021-01-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='nemesis_n_agency_model',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=200, null=True)),
                ('managerId', models.CharField(max_length=45, null=True)),
                ('vat', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=45, null=True)),
                ('phone', models.CharField(max_length=45)),
                ('certification', models.CharField(max_length=45, null=True)),
                ('customerId', models.CharField(max_length=20, null=True)),
                ('moreInfo', models.CharField(default='', max_length=250)),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('version', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='nemesis_n_contact_model',
            fields=[
                ('name', models.CharField(max_length=45)),
                ('surname', models.CharField(max_length=45)),
                ('taxCode', models.CharField(max_length=16)),
                ('address', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=45)),
                ('user', models.CharField(max_length=20)),
                ('customerId', models.CharField(max_length=20)),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('version', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='nemesis_n_customer_model',
            fields=[
                ('name', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=250)),
                ('vat', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=45)),
                ('phone', models.CharField(max_length=45)),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('version', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='nemesis_n_ticket_model',
            fields=[
                ('createdBy', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('INS', 'Instalation'), ('INT', 'Integration'), ('MAN', 'Maintenance'), ('DIS', 'Uninstall'), ('SUP', 'Support'), ('IND', 'Integration Delivery'), ('MND', 'Maintenance Delivery')], max_length=3)),
                ('customerId', models.CharField(max_length=20)),
                ('creationDate', models.DateField()),
                ('status', models.CharField(choices=[('OPENED', 'Open Ticket'), ('MANAGING', 'Managing Ticket'), ('WORKING', 'Working Ticket'), ('RESOLVED', 'Resolved Ticket'), ('REJECTED', 'Rejected Ticket'), ('ABORTED', 'Aborted Operation')], max_length=8)),
                ('priority', models.CharField(choices=[('LOW', 'Low Priority'), ('NORMAL', 'Normal Priority'), ('HIGH', 'High Priority')], max_length=6)),
                ('agencyId', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('version', models.IntegerField()),
                ('code', models.CharField(max_length=45)),
            ],
        ),
    ]
